name: Build and Release

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          vs-version: '17.0'
          msbuild-architecture: x64

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14.1
        with:
          cmake-version: '3.20'

      - name: Determine version
        id: determine_version
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.1")
          echo "::set-output name=version::$latest_tag"
        shell: bash

      - name: Configure crymachina_rpc CMake Release
        run: cmake -B build_crymachina_rpc -S crymachina_rpc -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build crymachina_rpc Release
        run: cmake --build build_crymachina_rpc --config Release

      - name: Increment version
        id: version
        run: |
          $version = Get-Content version
          Set-Content -Path version -Value ($version + 1)
          Write-Host "Version number incremented to $version"
        shell: pwsh

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: 'build_crymachina_rpc/Release/libScePad.dll'
          draft: false
          prerelease: false
          tag_name: v${{ steps.version.outputs.version }}
          title: Release v${{ steps.version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
